# Generated by Django 2.0.1 on 2018-01-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_tag', models.CharField(max_length=120)),
                ('player_icon', models.CharField(max_length=120)),
                ('char_one_name', models.CharField(max_length=50)),
                ('char_one_image', models.CharField(max_length=120)),
                ('char_two_name', models.CharField(max_length=50)),
                ('char_two_image', models.CharField(max_length=120)),
                ('char_three_name', models.CharField(max_length=50)),
                ('char_three_image', models.CharField(max_length=120)),
                ('char_four_name', models.CharField(max_length=50)),
                ('char_four_image', models.CharField(max_length=120)),
                ('char_five_name', models.CharField(max_length=50)),
                ('char_five_image', models.CharField(max_length=120)),
                ('elims_stat', models.CharField(max_length=50)),
                ('heals_stat', models.CharField(max_length=50)),
            ],
        ),
    ]
